version: '3'
services:
  staticsite:
    build: ./app
    image: staticsite:latest
    ports: 
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:7.8.1
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"
    environment: 
      - "discovery.type=single-node"

  kibana:
    image: kibana:7.8.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"